### ISSUE TITLE
Bring up Kubernetes Cluster

### ISSUE THREAD

**Issue by Rajalakshmi-Girish-Persistent** [vasavi-27/Tasks#1]
This task is to bring up a single node `Kubernetes` Cluster on the centos VM (which you created on Free Bird) using `kubeadm init`
- Need to document the steps you followed.
- Reference links
      - https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/create-cluster-kubeadm/
      - https://github.com/ppc64le-cloud/test-infra/wiki/Creating-Kubernetes-cluster-with-kubeadm-on-Power-(RHEL-or-CentOS)

**Duration for task completion:** 3 days from the start of the task.

**Comment by Rajalakshmi-Girish-Persistent** [comment]
Also refer : https://www.mirantis.com/blog/how-install-kubernetes-kubeadm/

**Comment by Rajalakshmi-Girish-Persistent** [comment]
Also, refer : https://computingforgeeks.com/install-kubernetes-cluster-on-centos-with-kubeadm/

**Comment by vasavi-27** [comment]
Started on 13th December

**Comment by vasavi-27** [comment]
Due to unsigned authority images not pulled from the internet for that i have installed ssl on my vm and and kubelet is not running due to that some errors my task has been delayed

**Comment by Rajalakshmi-Girish** [comment]
@vasavi-27 could complete this task after help in debugging.
She had errors as she missed to enable SystemdCgroup in containerd's `config.toml`
Also, there were failures in `kubelet` and node details which were debugged and fixed.

**Comment by Rajalakshmi-Girish-Persistent** [comment]
@vasavi-27 could complete this task after help in debugging.
She had errors as she missed enabling `SystemdCgroup` in containerd's `config.toml`
Also, there were failures in `kubelet` and node details which were debugged and fixed.

**Comment by Rajalakshmi-Girish-Persistent** [comment]
@vasavi-27 Kindly post the commands for the following activities:
1. Find the kubelet logs
2. Find the containerd logs
3. watch for pod statuses running in all namespaces
4. Look at the pod logs
5. Describe the node and grep for taints
6. Start kublet/containerd services
Also update a simple document with steps followed to bring up the cluster.

**Comment by vasavi-27** [comment]
1.journalctl -xeu kubelet > kubelet.log
2.kubectl logs (containerd name)
3. watch kubectl get pods -A
4.kubectl logs pod_name
5.kubectl describe node <node name > -n <name space)
6.systemctl start kubelet, systemctl start containerd

**Comment by Rajalakshmi-Girish-Persistent** [comment]
[kubernetes.txt](https://github.com/vasavi-27/Tasks/files/10306242/kubernetes.txt)
The cluster is successfully up and the document was created by Vasavi with the steps she followed.
Hence closing the task.
