### ISSUE TITLE
Run kubernetes conformance tests with regex [sig-cli]

### ISSUE THREAD

**Issue by Rajalakshmi-Girish-Persistent** [vasavi-27/Tasks#10]
This task is to run the [sig-cli] Conformance tests in https://github.com/kubernetes/kubernetes/tree/master/test/e2e

1. git clone https://github.com/kubernetes/kubernetes.git
2. cd kubernetes/
make WHAT=test/e2e/e2e.test
3. Explore how to frame a command with ./e2e.test binary and run the [sig-cli] conformance tests.
Note: You must pass the kubeconfig and focus values to the binary using ginkgo.

**Comment by Rajalakshmi-Girish-Persistent** [comment]
@vasavi-27 As mentioned earlier, please describe how you completed the task before closing it.
Provide details with steps.

**Comment by vasavi-27** [comment]
steps to run [sig-cli] in conformance tests

1. By using git clone I have cloned the kubernetes reposistory
2. By using cd We get into kubernetes directory 
3. Then in that directory we need to run e2e.test by using make command
4. I used below command to run only sig-cli in conformance tests with regular expressions
` ./_output/bin/e2e.test --ginkgo.focus="\[sig-cli\].*\[Conformance\]$" --provider=local  --kubeconfig=/etc/kubernetes/admin.conf`
