### ISSUE TITLE
Create a Pod that used PVC

### ISSUE THREAD

**Issue by Rajalakshmi-Girish-Persistent** [vasavi-27/Tasks#6]
1. Create a Persistent Volume of `type` local and `storageClass` manual with a 2G capacity. (Accessmode ReadWriteOnce)
2. Create a PVC with storage request 1G 
3. Create a Pod that uses the above PVC.
4. Add data to local storage and view the changes in Pod's mount Path (Display the steps that show this)

**Comment by Rajalakshmi-Girish-Persistent** [comment]
@vasavi-27 You may use https://github.com/swapnil-kulkarni-training/kubernetes-training/tree/main/volume

**Comment by vasavi-27** [comment]
**steps for viewing changes in pod mount path**

1. First ssh into inside a container
2. Then inside container In cd//var/lib/mysql mount path 
3. created myfile.txt
4. But in my local machine unable to find the myfile.txt

**Comment by vasavi-27** [comment]
1. From the above  Swapnil repository I have used yaml files for creating pvc and pv

**Steps for Data to local storage viewing changes in the pod mount path**  

1. ` First ssh into a container`
2. `And then inside container In cd /var/lib/mysql created file using touch command`
3. `In mount path cd /var/lib/mysql file is created`
4. `Then in pod mount path cd "/mnt/site-data" file is displayed which created in cd/var/lib/mysql mount path`

**Output for view changes in pod mount path** kubectl exec -it my-lamp-site c -- bin/bash
Defaulted container "mysql" out of: mysql, php
bash-4.4# cd /var/lib/mysql
bash-4.4# ls
'#ib_16384_0.dblwr'  '#innodb_temp'   binlog.000002   ca.pem            ib_buffer_pool   myfile.txt   mysql.sock           public_key.pem    sys
'#ib_16384_1.dblwr'   auto.cnf        binlog.index    client-cert.pem   ibdata1          mysql        performance_schema   server-cert.pem   undo_001
'#innodb_redo'        binlog.000001   ca-key.pem      client-key.pem    ibtmp1           mysql.ibd    private_key.pem      server-key.pem    undo_002
bash-4.4# exit
exit
[root@hj-ibmibm14872 attuluri_vasavi]# cd "/mnt/site-data"
[root@hj-ibmibm14872 site-data]# ls
html  mysql
[root@hj-ibmibm14872 site-data]# cd mysql
[root@hj-ibmibm14872 mysql]# ls
auto.cnf       binlog.index  client-cert.pem    #ib_16384_1.dblwr  ibtmp1        myfile.txt  mysql.sock          public_key.pem   sys
binlog.000001  ca-key.pem    client-key.pem     ib_buffer_pool     #innodb_redo  mysql       performance_schema  server-cert.pem  undo_001
binlog.000002  ca.pem        #ib_16384_0.dblwr  ibdata1            #innodb_temp  mysql.ibd   private_key.pem     server-key.pem   [undo_002`]`


`
