### ISSUE TITLE
Run the unit test suite of upstream kubernetes

### ISSUE THREAD

**Issue by Rajalakshmi-Girish-Persistent** [vasavi-27/Tasks#9]
Run and produce the output of unit tests in https://github.com/kubernetes/kubernetes

**Comment by Rajalakshmi-Girish-Persistent** [comment]
Steps on high level:
1. Install latest stable golang
2. Clone above repo and cd into it
3. Run command  make test KUBE_RACE=-race

**Comment by Rajalakshmi-Girish-Persistent** [comment]
Vasavi sent across below file with test results:
[make test.txt](https://github.com/vasavi-27/Tasks/files/10543945/make.test.txt)
Can you follow the below steps to see if the errors in the above file are avoided:

- git clone https://github.com/kubernetes/kubernetes
- cd kubernetes
-  export KUBE_TIMEOUT='--timeout=600s'
-  export KUBE_KEEP_VERBOSE_TEST_OUTPUT=y
- export LOG_LEVEL=4
- wget -q -O /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/3.4.1/yq_linux_ppc64le
- chmod +x /usr/local/bin/yq
- pushd ./build/
- GOLANG_VERSION=`yq read dependencies.yaml 'dependencies(name==golang: upstream*).version'`
- popd
- url="https://storage.googleapis.com/golang/go${GOLANG_VERSION}.linux-ppc64le.tar.gz"
- wget -O go.tgz "$url" --progress=dot:giga
- rm -rf /usr/local/go
- tar -C /usr/local -xzf go.tgz
- make test KUBE_RACE=-race

**Comment by vasavi-27** [comment]
By following the above steps also getting same errors so we are closing this task
